server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  metrics:
    export:
      stackdriver:
        enabled: true
        step: 1m
        project-id: phonic-operand-457319-e2
        resource-type: "gce_instance"  # Or k8s_container
        metric-type-prefix: "prometheus.googleapis.com/myapp/"
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: metrics-demo

  endpoint:
    health:
      show-details: always
